### ISSUE TITLE
Client.py not working

### ISSUE THREAD

**Issue by JafferWilson** [FrancescoSaverioZuppichini/TensorFlow-Serving-Example#1]
This is what I got when I try to run client.py:

```
C:\Users\jaffer\Desktop\TensorFlow-Serving-Example-master>python client.py
 * Running on http://localhost:3000/ (Press CTRL+C to quit)
Input: [[2, 3], [1, 2]]
<_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
Prediction failed!
output: {}
[2018-10-31 6:48:35,389] ERROR in app: Exception on /prediction [POST]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "client.py", line 35, in get_prediction
    return jsonify({ 'predictions': prediction['outputs'].tolist() })
KeyError: 'outputs'
127.0.0.1 - - [31/Oct/2018 6:48:35] "[1m[35mPOST /prediction HTTP/1.1[0m" 500 -
127.0.0.1 - - [31/Oct/2018 6:59:16] "[33mPOST /prediction/ HTTP/1.1[0m" 404 -
```
Please let know what is the problem

**Comment by FrancescoSaverioZuppichini** [comment]
Hello,

First of all, usually educated people ask nicely and provide every information, like operating system, tf version and so on. I bet you didn't even try to place a breakpoint and look for the value of prediction.

Cheers,
Francesco

**Comment by JafferWilson** [comment]
@FrancescoSaverioZuppichini My apologize if this offend you Sir.
Well, I will give you details you want to know.
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home Edition

Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: I dont know that. I am using desktop PC.

TensorFlow installed from (source or binary): pip

TensorFlow version (use command below): b'v1.10.0-rc1-19-g656e7a2b34' 1.10.0

Python version: Python 3.5

Bazel version (if compiling from source): ?

GCC/Compiler version (if compiling from source): ?

CUDA/cuDNN version: 9.0

GPU model and memory: Not available right now.

I have tried using the Print statements to verify whether input is properly accepted and whether it is reaching for output or not. In my question, you will see I have printed Input and output values. The Input reached properly. Out put is a blank quotes. Hence, no key was found No output on the screen.
Please let me know if anything else is required. I will be happy to share it with you.

**Comment by FrancescoSaverioZuppichini** [comment]
I will have to try again to run the whole stuff on my machine. Keep in mind two things:

1) They probably changed something in tensorflow serving but in theory, since we are pulling a docker image that should work
2) If you see no output then it probably means two things. Or there is a connection problem with tensorflow serving or there is a problem with the model itself, maybe you passed the wrong tensor to as output? 

Btw, no offense taken. A stupid question, do you run the docker image?

**Comment by JafferWilson** [comment]
No, I haven't gone with the docker. I downloaded the code from github repository and have placed it in the same folder where the project is running. I didn't got any issues related to library, but there is no output while running it. I have seen that you have share a model/checkpoint with the project. I tried to run the same.

**Comment by FrancescoSaverioZuppichini** [comment]
Please read the article, how can you expect to have an output if you don't run the docker image?
